# RL from Scratch - Python introduction

This is a quick intoduction to Python and the features that will be used in the exercises. Take a look at the following examples for a quick overview of how Python can be used. For a more thorough introduction you can take a look at the [official documentation](https://www.python.org/about/gettingstarted/), which contains some tutorials and/or lessons.

These exercises assume you already have programming experience, so this document will only show you how certain constructs work in Python.

# Jupyter

These exercises will use Python notebooks hosted on a Jupyter Hub.

Python notebooks are basically interactive Python consoles hosted in a document-like website. Lines of code (or documentation) are bundled in cells. Each cell can be executed by either pressing `CTRL+ENTER` or `SHIFT+ENTER` on your keyboard or pressing the 'run' button in the toolbar. The output will be shown under the cell.

In [1]:
print('Hello, world!')

Hello, world!


## Modules

Python uses modules that can be imported into your file. There are two ways of importing, importing a whole module with the `import` directive, followed by an optional shorthand name. Or you can import only a single component (e.g. class or function) from a method using the `from .. import` directive.

In [2]:
import numpy as np
from datetime import datetime

## Functions

Functions are defined using the `def` keyword like below. Don't forget the `:` after the parameter list.

There are no start or end of block delimiters. Blocks of code are grouped by using the same indentation level.

In [3]:
def multiply(a, b):
    return a * b

multiply(2,3)

6

Functions parameters can be assigned to by name. Particular useful when a function has default values for parameters.

In [4]:
def mul3(a, b, c=1):
    return a * b * c

mul3(4, 3, c=2)

24

Python supports tuples that can be "unpacked" automatically into separate variables.

In [5]:
def return_stuff():
    return 42, 1337

a, b = return_stuff()
print(a)
print(b)

42
1337


## Lists

Arrays are represented in Python by lists `[]`. You can initialize them as follows.

In [6]:
a = [1,2,3,4]
a

[1, 2, 3, 4]

Or initialize them empty, and then add items to them.

In [7]:
a = []
a.append(1)
a.append(2)
a

[1, 2]

You can grab the length of the list.

In [8]:
len(a)

2

Lists can contain lists.

In [9]:
a = [[1,2,3],[4,5,6]]
a

[[1, 2, 3], [4, 5, 6]]

In [10]:
len(a)

2

Accessing items can be done with the index operator `[x]`.

In [11]:
a[0]

[1, 2, 3]

In [12]:
a[0][1]

2

## Branching

Python `for`-loops are basically iterators over a collection. You can iterate over a list.

In [13]:
A = [1,2,3,4]
for a in A:
    print(a)

1
2
3
4


Or you can create an iterator with the `range` function.

In [14]:
for i in range(4):
    print(i)

0
1
2
3


Loops can be done in-place.

In [15]:
[i * 2 for i in range(4)]

[0, 2, 4, 6]

If statements support "if", "else if", "else" structure.

Note: no bracked `()` required around guards.

In [16]:
a = 100
if a == 42:
    print('ok')
elif a == 100:
    print('meh')
else:
    print('booh')

meh


## NumPy

[NumPy](https://numpy.org) is a Python library that adds a lot of functionality for "scientific computing". It mainly adds useful operations on multi-dimensional arrays.

In [17]:
a = np.array([[1,2,3],[4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

This array has 2 dimensions (also called axes). In this case you can regard it as 2 rows of 3 columns.

In [18]:
a.shape

(2, 3)

Items can be accessed using a multi-dimensional indexer.

In [19]:
a[1,2]

6

The ':' operator can be used to access all items in that axis/dimension.

In [20]:
a[:,2]

array([3, 6])

NumPy adds basic operations like adding a scalar value to an array.

In [21]:
a += 10
a

array([[11, 12, 13],
       [14, 15, 16]])

Or subtracting a row from all rows.

In [22]:
a -= [1,2,3]
a

array([[10, 10, 10],
       [13, 13, 13]])

You can get statistics of the array like the mean of the entire array.

In [23]:
a = [[1,2,3],[4,5,6]]
np.mean(a)

3.5

Or the mean of the first dimension.

In [24]:
np.mean(a, axis=0)

array([2.5, 3.5, 4.5])

Or mean of the second dimension.

In [25]:
np.mean(a, axis=1)

array([2., 5.])

You can also search in arrays, like the index of the maximum value.

In [26]:
a = [1, 2, 2, 6, 1]
np.argmax(a)

3

# Done

That's basically all you need to know in order to start with the exercises. Good luck!